### ISSUE TITLE
Firmware version in LoRa payload

### ISSUE THREAD

**Issue by HarveyBates** [DPIclimate/enviro-node#3]
A LoRa packet on startup (perhaps at intervals as well) should contain the firmware version (e.g. `v1.0.1`).

Perhaps this should contain firmware from both sensor micro and telemetry micro.

**Comment by dajtxx** [comment]
If we make this periodic, such as daily, we can use a confirmed uplink to check the session is still valid.

We could also include known sensor info in this message, based upon an SDI-12 bus query. That won't cover analogue and digital inputs though.

We also need to think how this fits with other transports.

**Comment by dajtxx** [comment]
We decided against including LoRaWAN.
