### ISSUE TITLE
On-site node reboot without opening enclosure

### ISSUE THREAD

**Issue by dpi-mick** [DPIclimate/enviro-node#4]
Allow a node to be rebooted by pressing a button on the node enclosure or by holding a magnet against it the enclosure or some other means that doesn't involve opening the enclosure.

The use case here is to allow an on-site person to reboot a node if it's having a problem, has dropped it's cellular connection etc.

The magnet option might be useful if the node enclosure is not easily accessible. e.g. up a tree, on a pole etc. 

Audible feedback of reboot would be useful.

**Comment by HarveyBates** [comment]
Have external device reboot in next version without opening enclosure with audible feedback.

BEEP BOP! 😀
