### ISSUE TITLE
Node Maintenance Mode

### ISSUE THREAD

**Issue by dpi-mick** [DPIclimate/enviro-node#6]
Allow a node to be placed into "maintenance" mode, such that it does not uplink data points.

This would allow maintenance actions to take place without impact on data quality. e.g. sensor replacements.

Ideally, the node would still be polling sensors, and may still uplink data, but the uplink message may have a "maintenance" flag so the data received does not get added to the database.

**Comment by HarveyBates** [comment]
added external push button that could enable this function, or it may be enabled in the app after pressing the push button
