### ISSUE TITLE
Sensor connectors (Internal or External)

### ISSUE THREAD

**Issue by HarveyBates** [DPIclimate/enviro-node#7]
Continuing from #4, we have two options for connecting sensors to the circuit board: 
1. Connections outside the box - don't have to open the box to connect a sensor. Has the disadvantage of longer setup time taken to assemble the board and perhaps higher cost. Has the advantage of not needing to open the enclosure to add a new sensor.
2. Connections inside the box - cables route into the enclosure. Pluggable screw terminals can be used but will require that for a new sensor to be added, the enclosure must be opened.

**Comment by HarveyBates** [comment]
Panel mount system could be assembled offsite. Would need a template to drill holes in enclosures. Multiple plugs could allow for individual SDI-12 addresses. Still faces the problem of conflicting addresses on new devices (even though they should all be address 0, some aren't).

**Comment by dajtxx** [comment]
The design has been finalised.
