### ISSUE TITLE
External USB Socket

### ISSUE THREAD

**Issue by dpi-mick** [DPIclimate/enviro-node#9]
Include an external USB Socket (with weather cap).

Something like the following (but less costly!!):-

[https://au.element14.com/multicomp-pro/mp002448/usb-type-c-r-a-ip68-sealed-connector/dp/3369657?gclid=EAIaIQobChMIw7v1jdOY-gIVzgRyCh01vA2CEAQYDCABEgIAJPD_BwE&mckv=_dc|pcrid||pkw||pmt||slid||product|3369657|pgrid||ptaid||&CMP=KNC-GAU-GEN-SHOPPING-PLA-PMAX](url)

**Comment by HarveyBates** [comment]
cant afford this at this time 😞
